App_Dashboard/urls.py
from django.urls import path
from App_Dashboard import views

app_name = 'App_Dashboard'

urlpatterns = [
    path('', views.home, name="home"),

    path('designer_info/', views.designer_info, name='designer_info'),
    path('add_designer/', views.add_designer, name='add_designer'),
    path('view_designer/<int:designer_id>/', views.view_designer, name='view_designer'),
    path('edit_designer/<int:designer_id>/', views.edit_designer, name='edit_designer'),
    path('delete_designer/<int:designer_id>/', views.delete_designer, name='delete_designer'),

    path('post/', views.post, name='post'),
    path('view_posts/', views.view_posts, name='view_posts'),
    path('view_post/<int:post_id>/', views.view_post, name='view_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),


    path('react_post/<int:post_id>/', views.react_post, name='react_post'),

    path('reply/', views.reply, name='reply'),
    path('desginerMessage/', views.desginerMessage, name='desginerMessage'),
    path('messageReply/<int:message_id>', views.designerMessageReply, name='messageReply'),
    path('myMessageList/', views.myMessageList, name='myMessageList'),

    path('contact_us/', views.contactUs, name='contact_us'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('users/', views.users, name='users'),
    path('log-sign/', views.log_sign, name='log-sign'),
    path('login/', views.login, name='login'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Dashboard import views

admin.site.site_header = 'Havenly'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('dashboard/', include('App_Dashboard.urls')),
    path('', views.home, name="home")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
# from App_Dashboard.models import Country


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    # country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name="country_user_profile", default=None)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    contact = models.CharField(max_length=20, null=True)
    dob = models.DateField(blank=True, null=True)
    status_ = (
        (1, "Active"),
        (2, "Deactivate")
    )
    status = models.IntegerField(choices=status_, null=True)
    type_ = (
        (1, "Customer"),
        (2, "Designer")
    )
    type = models.IntegerField(choices=type_)

    def __str__(self):
        return self.full_name

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from App_Login.models import UserProfile


class CreateNewUser(UserCreationForm):
    email = forms.EmailField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password1 = forms.CharField(
        required=True, label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )
    password2 = forms.CharField(
        required=True, label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password Confirm'})
    )

    class Meta:
        model = User
        fields = ('email', 'username', 'password1', 'password2')


class EditProfile(forms.ModelForm):
    dob = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = UserProfile
        exclude = ('user', 'type')

App_Login/views.py
import os

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from django.template.context_processors import media

from App_Dashboard.forms import PostForm
from App_Dashboard.models import Post
from App_Login.forms import CreateNewUser, EditProfile
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as lg
from django.urls import reverse, reverse_lazy
from App_Login.models import UserProfile

# Create your views here.

def login(request):
    return redirect('App_Login:log-sign')

def log_sign(request):
    if request.method == 'POST' and 'signin' in request.POST:
        username1 = request.POST.get('username')
        password1 = request.POST.get('password')
        user = authenticate(username=username1, password=password1)
        if user is not None:
            lg(request, user)
            return redirect('App_Dashboard:home')
    if request.method == 'POST' and 'signup' in request.POST:
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password1']
        user = User.objects.create_user(username=username, password=password, email=email)
        user.save()
        registered = True
        data_dict = {
            'user_id': user.id,
            'type': request.POST['type'],
        }
        UserProfile.objects.create(**data_dict)
        return HttpResponseRedirect(reverse('App_Login:log-sign'))

    return render(request, 'App_Login/log_sign.html', context={'title': 'Sign In/Sign Up'})

@login_required
def edit_profile(request):

    if request.user.is_superuser:
        messages.error(request, 'You are a superuser')
        return HttpResponseRedirect(reverse('App_Login:profile'))

    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)

    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)

        if request.FILES and request.POST.get('profile_pic-clear'):
            pass
        else:
            if request.FILES:
                if request.user.user_profile.profile_pic:
                    if os.path.exists(request.user.user_profile.profile_pic.path):
                        os.remove(request.user.user_profile.profile_pic.path)

            if request.POST.get('profile_pic-clear'):
                if request.user.user_profile.profile_pic:
                    if os.path.exists(request.user.user_profile.profile_pic.path):
                        os.remove(request.user.user_profile.profile_pic.path)

        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)
            messages.success(request, 'Profile Updated')
            return HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/edit-profile.html', context={'title': 'Edit Profile', 'form': form})


@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:log-sign'))


@login_required
def profile(request):
    form = PostForm()
    diction = {
        'title': 'User List',
        'form': form
    }
    return render(request, 'App_Login/user.html', context=diction)

@login_required
def users(request):
    users = UserProfile.objects.filter(type=2)
    print(users)
    diction = {
        'title': 'User List',
        'users': users
    }
    return render(request, "App_Login/users.html", context=diction)

templates/App_Login/edit-profile.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="/static/css/posts.css" />
    <link
      href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
      rel="stylesheet"
    />
    <link
      href="http://fonts.googleapis.com/css?family=Montserrat:300,400,700"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,600i,700,700i"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/static/css/style.css" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/static/css/style3.css" />
    <link rel="stylesheet" href="/static/css/style5.css" />

    {% include 'footer_scripts.html' %}

    <title>Havenly</title>
  </head>
  <body>
    <style>
      .bg-scollme {
        background: rgba(0, 0, 0, 0.5);
      }
      .btn-contact-bg {
        background: #000 none repeat scroll 0 0 !important;
        border: 1px solid #000 !important;
      }
    </style>
    <!-- NAV-BAR -->
    {% include 'navbar.html' %}
    <!-- END -->

<div class="container" style="margin-top: 150px; margin-bottom: 150px;">
    <form method="post" enctype="multipart/form-data">
        {% if user.user_profile.profile_pic %}
        <img src="/media/{{ user.user_profile.profile_pic }}" alt="" width="100px" height="100px" class="img-responsive">
        {% endif %}
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" name="button" class="btn btn-primary">Submit</button>
    </form>
</div>

    {% comment %} footer {% endcomment %} {% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://kit.fontawesome.com/abffacff72.js" crossorigin="anonymous"></script>
    <script src="/static/js/posts_scripts.js"></script>
  </body>
</html>

templates/App_Login/log_sign.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/css/style.css" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/static/css/style2.css" />
    <link rel="stylesheet" href="/static/css/style.css" />
    <script src="https://unpkg.com/ionicons@latest/dist/ionicons.js"></script>
    {% include 'footer_scripts.html' %}

    <title>Sign In/Sign Up</title>
  </head>
  <body>
    {% include 'navbar.html' %}

    <!-- Login signup -->
    <div class="sign-up-body">
      <div class="container-log-sign-in" id="container">
        <div class="form-container sign-up-container">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="log-sign-h1">Create Account</h1>
            <div class="social-container">
              <a href="#" class="social log-sign-link"
                ><ion-icon name="logo-facebook"></ion-icon
              ></a>
              <a href="#" class="social log-sign-link"
                ><ion-icon name="logo-google"></ion-icon
              ></a>
              <a href="#" class="social log-sign-link"
                ><ion-icon name="logo-linkedin"></ion-icon
              ></a>
            </div>
            <span class="log-sign-span"
              >or use your email for registration</span
            >
            <input
              class="form__input log-sign-input"
              type="text"
              placeholder="John Doe"
              required="required"
              name="username"
            />
            <input
              class="form__input log-sign-input"
              type="email"
              placeholder="you@example.com"
              required="required"
              name="email"
            />
            <input
              class="form__input log-sign-input"
              type="password"
              placeholder="• • • • • • • •"
              required="required"
              minlength="8"
              name="password1"
            />
            <input
              class="form__input log-sign-input"
              type="password"
              placeholder="• • • • • • • •"
              required="required"
              minlength="8"
              name="password2"
            />
            <select
              class="forn_input log-sign-input log-sign-select"
              required
              name="type"
              id="id_type"
            >
              <option value="">Select User Type:</option>
              <option value="1">As a Customer</option>
              <option value="2">As a Designer</option>
            </select>
            <button class="btn-sign-up" type="submit" name="signup">
              Sign Up
            </button>
          </form>
        </div>
        <div class="form-container sign-in-container">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="log-sign-h1">Sign in</h1>
            <div class="social-container">
              <a href="#" class="social log-sign-link"
                ><ion-icon name="logo-facebook"></ion-icon
              ></a>
              <a href="#" class="social log-sign-link"
                ><ion-icon name="logo-google"></ion-icon
              ></a>
              <a href="#" class="social log-sign-link"
                ><ion-icon name="logo-linkedin"></ion-icon
              ></a>
            </div>
            <span class="log-sign-span">or use your account</span>
            <input
              class="form__input log-sign-input"
              type="text"
              placeholder="John Doe"
              required="required"
              name="username"
            />
            <input
              class="form__input log-sign-input"
              type="password"
              placeholder="• • • • • • • •"
              required="required"
              minlength="8"
              name="password"
            />
            <a class="log-sign-link" href="#">Forgot your password?</a>
            <button class="btn-sign-up" type="submit" name="signin">
              Sign In
            </button>
          </form>
        </div>
        <div class="overlay-container">
          <div class="overlay">
            <div class="overlay-panel overlay-left">
              <h1 class="log-sign-h1">Welcome Back!</h1>
              <p>
                To keep connected with us please login with your personal info
              </p>
              <button class="ghost btn-sign-up" id="signIn">Sign In</button>
            </div>
            <div class="overlay-panel overlay-right">
              <h1 class="log-sign-h1">Hello, Friend!</h1>
              <p>Enter your personal details and start journey with us</p>
              <button class="ghost btn-sign-up" id="signUp">Sign Up</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% comment %} footer {% endcomment %}
    {% include 'footer.html' %}
    <!-- End -->
  </body>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  <script src="/static/js/index.js"></script>
</html>

templates/App_Login/user.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="/static/css/posts.css" />
    <link
      href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
      rel="stylesheet"
    />
    <link
      href="http://fonts.googleapis.com/css?family=Montserrat:300,400,700"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,600i,700,700i"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/static/css/style.css" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/static/css/style3.css" />
    <link rel="stylesheet" href="/static/css/style5.css" />

    {% include 'footer_scripts.html' %}

    <title>Havenly</title>
  </head>
  <body>
    <style>
      .bg-scollme {
        background: rgba(0, 0, 0, 0.5);
      }
      .btn-contact-bg {
        background: #000 none repeat scroll 0 0 !important;
        border: 1px solid #000 !important;
      }
    </style>
    <!-- NAV-BAR -->
    {% include 'navbar.html' %}
    <!-- END -->
    <div class="container" style="margin-top: 150px; margin-bottom: 150px;">
        <div class="row">
            <div class="col-sm-4">
                {% if user.user_profile.profile_pic %}
                <img src="/media/{{ user.user_profile.profile_pic }}" width="250px" height="250px" class="rounded-circle" alt="">
                {% else %}
                <img src="/media/default.jpg" width="250px" height="250px" class="rounded-circle" alt="">
                {% endif %}
            </div>
            <div class="col-sm-8">
                <h3>
                  <h3>{% if not user.user_profile.full_name %}
                    {{ user.username }}
                    {% else %}
                    {{ user.user_profile.full_name }}
                    {% endif %}
                  &nbsp;</h3>
                  <h5>Username: {{ user.username }}</h5>
                  <h5>Email: {{ user.email }}</h5>
                  <h5>Contact: {{ user.user_profile.contact }}</h5>
                  <br><br>
                  
                    <a href="{% url 'App_Login:edit' %}" class="btn btn-info"><i class="fas fa-edit mr-1"></i>Edit Profile</a>
                    <!-- Button trigger modal -->
                    {% if user.user_profile.type == 2 %}
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
                        <i class="fas fa-plus mr-1"></i>Add Design
                    </button>
                    {% endif %}
                </h3><br>
    
            </div>
        </div>
    </div>
    
    {% if user.user_profile.type == 2 %}
    <div class="container mt-5">
    
        <div class="row">
            {% for post in user.post.all %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail"
                         alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;"
                         src="/media/{{post.image}}" data-holder-rendered="true">
                    <div class="card-body" >
                        <p class="card-text" style="height: 90px; width: 100%; display: block;">{{ post.description|truncatewords:5 }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'App_Dashboard:view_post' post_id=post.id %}" class="btn btn-sm btn-outline-secondary" ><i class="fas fa-eye"> View</i></a>
                                <a href="{% url 'App_Dashboard:edit_post' post_id=post.id %}" class="btn btn-sm btn-outline-secondary" ><i class="fas fa-edit"> Edit</i></a>
                                <a href="{% url 'App_Dashboard:delete_post' post_id=post.id %}" class="btn btn-sm btn-outline-danger"><i class="fas fa-trash "> Delete</i></a>
                            </div>
                        </div>
                        <div><small class="text-muted">{{ post.upload_date}}</small></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endif %}
    
    
    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Add Design Blog</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="{% url 'App_Dashboard:post' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
    
                    <div class="modal-body form-control">
                        {{ form|crispy }}
    <!--                    <label for="image"><b>Image</b></label><br>-->
    <!--                    .<input type="file" id="image" class="form-control" accept="image/*" onchange="loadFile(event)" name="image">-->
    <!--                    <img id="output" style="height: 300px; width: auto"/> <br>-->
    <!--                    <label for="description"><b>Write Description</b></label>-->
    <!--                    <textarea name="description" class="form-control" id="description" cols="30" rows="10"></textarea>-->
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <input type="submit" value="Save" class="btn btn-primary btn-block">
                    </div>
                </form>
            </div>
        </div>
    </div>
    
    <script>
      var loadFile = function(event) {
        var output = document.getElementById('output');
        output.src = URL.createObjectURL(event.target.files[0]);
        output.onload = function() {
          URL.revokeObjectURL(output.src) // free memory
        }
      };
    </script>

    {% comment %} footer {% endcomment %} {% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script src="https://kit.fontawesome.com/abffacff72.js" crossorigin="anonymous"></script>
    <script src="/static/js/posts_scripts.js"></script>
  </body>
</html>

templates/App_Login/users.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="/static/css/posts.css" />
    <link
      href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
      rel="stylesheet"
    />
    <link
      href="http://fonts.googleapis.com/css?family=Montserrat:300,400,700"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,600i,700,700i"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="/static/css/style.css" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/static/css/style3.css" />
    <link rel="stylesheet" href="/static/css/style5.css" />

    {% include 'footer_scripts.html' %}

    <title>Havenly</title>
  </head>
  <body>
    <style>
        .bg-scollme {
            background: rgba(0, 0, 0, 0.5);
          }
    </style>
    <!-- NAV-BAR -->
    {% include 'navbar.html' %}
    <!-- END -->

    {% comment %} Posts Start {% endcomment %}

    <!-- START BLOG -->
    <section id="blog" class="blog_section">
      <div class="container">
        <div class="row">
          <div class="col-md-12" data-aos="fade-up">
            <div class="section-title text-center wow zoomIn mt-40">
              <h2>Designers</h2>
              <span></span>
              <p>Our Designers</p>
            </div>
          </div>
          <!-- END COL -->
        </div>
        <!-- END ROW -->

        <div class="row">
          {% for designer in users %}
          <div class="col-lg-4 col-md-6" data-aos="fade-up">
            <div class="single_blog">
              <div class="blog_image">
                <img
                  class="blog-photo"
                  alt="Blog Photo"
                  src="/media/{{ designer.profile_pic }}"
                  width="600px"
                />
              </div>
              <div class="blog-text">
                <h4>
                    {% if not designer.full_name %}
                    {{ designer.user.username }}
                    {% else %}
                    {{ designer.full_name }}
                    {% endif %}
                </h4>
                <p class="card-text">{{ designer.user.email }}</p>
                <p class="card-text">{{ designer.contact }}</p>
                <div class="row justify-content-center">
                  <a
                  href="{% url 'App_Dashboard:view_designer' designer_id=designer.id %}"
                  class="btn btn-lg btn-danger btn-center h-align col-7"
                  >Go to Details</a>
                </div>
              </div>
            </div>
          </div>
          <!--- END COL -->
          {% empty %}
          <div class="container"><h3 align="center">NO POST FOUND</h3></div>
          {% endfor %}
        </div>
        <!--- END ROW -->
      </div>
      <!--- END CONTAINER -->
    </section>
    <!-- END BLOG -->

    {% comment %} footer {% endcomment %} {% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    {% comment %} <script src="/static/js/navbar.js"></script> {% endcomment %}
    <script src="/static/js/posts_scripts.js"></script>
  </body>
</html>