App_Dashboard/urls.py
from django.urls import path
from App_Dashboard import views

app_name = 'App_Dashboard'

urlpatterns = [
    path('', views.home, name="home"),

    path('designer_info/', views.designer_info, name='designer_info'),
    path('add_designer/', views.add_designer, name='add_designer'),
    path('view_designer/<int:designer_id>/', views.view_designer, name='view_designer'),
    path('edit_designer/<int:designer_id>/', views.edit_designer, name='edit_designer'),
    path('delete_designer/<int:designer_id>/', views.delete_designer, name='delete_designer'),

    path('post/', views.post, name='post'),
    path('view_posts/', views.view_posts, name='view_posts'),
    path('view_post/<int:post_id>/', views.view_post, name='view_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),


    path('react_post/<int:post_id>/', views.react_post, name='react_post'),

    path('reply/', views.reply, name='reply'),
    path('desginerMessage/', views.desginerMessage, name='desginerMessage'),
    path('messageReply/<int:message_id>', views.designerMessageReply, name='messageReply'),
    path('myMessageList/', views.myMessageList, name='myMessageList'),

    path('contact_us/', views.contactUs, name='contact_us'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('users/', views.users, name='users'),
    path('log-sign/', views.log_sign, name='log-sign'),
    path('login/', views.login, name='login'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Dashboard import views

admin.site.site_header = 'Havenly'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('dashboard/', include('App_Dashboard.urls')),
    path('', views.home, name="home")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Dashboard/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class DesignerInfo(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='profile_pics', blank=True)
    email = models.CharField(max_length=20)
    contact = models.CharField(max_length=20)
    status_ = (
        (1, "Active"),
        (2, "Deactivate")
    )
    status = models.IntegerField(choices=status_)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    image = models.ImageField(upload_to='post_images')
    description = models.TextField()
    upload_date = models.DateTimeField(auto_now_add=True)
    upload_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-upload_date',]

    def __str__(self):
        return self.description


class React(models.Model):
    post = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='react_user')



class ContactUs(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=20)
    contact = models.CharField(max_length=20)
    message = models.CharField(max_length=20)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Reply(models.Model):
    post_id = models.IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reply_user')
    message = models.TextField()

    def __str__(self):
        return self.message


class DesignerMessage(models.Model):
    designer_user = models.IntegerField()
    customer_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer_user')
    message = models.TextField()
    reply_message = models.TextField()

    def __str__(self):
        return self.message

App_Dashboard/forms.py
from django import forms
from App_Dashboard.models import DesignerInfo, Post, Reply, DesignerMessage


class DesignerInfoForm(forms.ModelForm):
    class Meta:
        model = DesignerInfo
        fields = '__all__'


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'description',]


class ReplyFrom(forms.ModelForm):
    class Meta:
        model = Reply
        fields = '__all__'


class DesignerMessageFrom(forms.ModelForm):
    class Meta:
        model = DesignerMessage
        fields = ['reply_message',]

App_Dashboard/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from App_Dashboard import forms
from App_Dashboard.forms import PostForm, ReplyFrom, DesignerMessageFrom
from App_Dashboard.models import DesignerInfo, Post, ContactUs, React, Reply, DesignerMessage
from App_Login.models import UserProfile


# @login_required
def home(request):
    # country_list = Country.objects.all()
    posts = Post.objects.all()
    customers_count = UserProfile.objects.filter(type=1)
    designers_count = UserProfile.objects.filter(type=2)
    designers = UserProfile.objects.filter(type=2)
    # aboutus = AboutUs.objects.all()
    diction = {
        'title': 'Dashboard',
        'customers_count': customers_count,
        'designers_count': designers_count,
        'designers': designers,
        'posts': posts
    }
    return render(request, "App_Dashboard/home.html", context=diction)


@login_required
def country(request):
    country_list = Country.objects.all()
    diction = {
        'title': 'Country_List',
        'country_list': country_list
    }
    return render(request, "App_Dashboard/country.html", context=diction)


@login_required
def country_form(request):
    form = forms.CountryForm()

    if request.method == 'POST':
        form = forms.CountryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request, 'Country Added Successfully')
            return HttpResponseRedirect(reverse('App_Dashboard:country'))
    diction = {
        'title': "Add Country",
        'country_form': form
    }
    return render(request, "App_Dashboard/country_form.html", context=diction)


@login_required
def edit_country(request, country_id):
    country_info = Country.objects.get(pk=country_id)
    form = forms.CountryForm(instance=country_info)

    if request.method == 'POST':
        form = forms.CountryForm(request.POST, instance=country_info)

        if form.is_valid():
            form.save(commit=True)
            messages.info(request, 'Country Updated Successfully')
            return HttpResponseRedirect(reverse('App_Dashboard:country'))
    diction = {
        'edit_form': form
    }
    return render(request, 'App_Dashboard/edit_country.html', context=diction)


@login_required
def delete_country(request, country_id):
    Country.objects.get(pk=country_id).delete()
    messages.success(request, 'Country Deleted Successfully')
    return HttpResponseRedirect(reverse('App_Dashboard:country'))


@login_required
def designer_info(request):
    designers = DesignerInfo.objects.all()
    print(designers)
    diction = {
        'title': 'Designer Info',
        'designers': designers,
    }
    return render(request, "App_Dashboard/designers_list.html", context=diction)


@login_required
def add_designer(request):
    form = forms.DesignerInfoForm()

    if request.method == 'POST':
        form = forms.DesignerInfoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request, 'Designer Info Added Successfully')
            return HttpResponseRedirect(reverse('App_Dashboard:designer_info'))
    diction = {
        'title': "Add Designer Info",
        'designer_info_form': form
    }
    return render(request, "App_Dashboard/designers_form.html", context=diction)


@login_required
def view_designer(request, designer_id):
    designer = UserProfile.objects.get(pk=designer_id)
    posts = Post.objects.filter(author_id=designer.user.id)

    diction = {
        'title': 'Designer Details',
        'designer': designer,
        'posts': posts,
    }
    return render(request, 'App_Dashboard/view_designers.html', context=diction)\


@login_required
def edit_designer(request, designer_id):
    designer_info = DesignerInfo.objects.get(pk=designer_id)
    form = forms.DesignerInfoForm(instance=designer_info)

    if request.method == 'POST':
        form = forms.DesignerInfoForm(request.POST, request.FILES, instance=designer_info)

        if form.is_valid():
            form.save(commit=True)
            messages.info(request, 'Designer Updated Successfully')
            return HttpResponseRedirect(reverse('App_Dashboard:designer_info'))
    diction = {
        'edit_form': form
    }
    return render(request, 'App_Dashboard/edit_designers.html', context=diction)


@login_required
def delete_designer(request, designer_id):
    DesignerInfo.objects.get(pk=designer_id).delete()
    messages.success(request, 'Designer Deleted Successfully')
    return HttpResponseRedirect(reverse('App_Dashboard:designer_info'))


@login_required
def post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(request, 'Designer Post Added Successfully')
            return HttpResponseRedirect(reverse('App_Login:profile'))
    diction = {
        'title': "Profile Info",
    }
    return render(request, "App_Login/user.html", context=diction)


def view_posts(request):
    posts = Post.objects.all()
    reacts = React.objects.all()

    diction = {
        'title': 'Blog Post',
        'posts': posts,
        'reacts': reacts,

    }
    return render(request, 'App_Dashboard/view_posts.html', context=diction)

@login_required
def view_post(request, post_id):
    posts = Post.objects.all()
    post = Post.objects.get(pk=post_id)
    replies = Reply.objects.filter(post_id=post_id)
    reacts = React.objects.filter(post=post_id, user=request.user)
    total_reacts = React.objects.filter(post=post_id)

    diction = {
        'title': 'Post Details',
        'post': post,
        'replies': replies,
        'reacts': reacts,
        'total_reacts': total_reacts,
        'posts': posts
    }
    return render(request, 'App_Dashboard/view_post.html', context=diction)

@login_required
def edit_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            form.save(commit=True)
            messages.info(request, 'Post Updated Successfully')
            return HttpResponseRedirect(reverse('App_Login:profile'))
    diction = {
        'edit_form': form
    }
    return render(request, 'App_Dashboard/edit_post.html', context=diction)


@login_required
def delete_post(request, post_id):
    Post.objects.get(pk=post_id).delete()
    messages.success(request, 'Post Deleted Successfully')
    return HttpResponseRedirect(reverse('App_Login:profile'))


def contactUs(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        contact = request.POST['contact']
        message = request.POST['message']
        data_dict = {
            'name': name,
            'email': email,
            'contact': contact,
            'message': message,
        }
        ContactUs.objects.create(**data_dict)
        messages.success(request, 'Message has been sent successfully ')
        return HttpResponseRedirect(reverse('App_Dashboard:home'))


def react_post(request, post_id):
    react = React.objects.filter(post=post_id, user=request.user)
    if react:
        react.delete()
        messages.error(request, 'You unlike the post successfully')
    else:
        data_dict = {
            'post': post_id,
            'user': request.user,
        }
        React.objects.create(**data_dict)
        messages.success(request, 'You like the post successfully')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def reply(request):
    if request.method == 'POST':
        data_dict = {
            'post_id': request.POST['post_id'],
            'user': request.user,
            'message': request.POST['message']
        }

        Reply.objects.create(**data_dict)
        messages.success(request, 'You comment replied successfully')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def desginerMessage(request):
    if request.method == 'POST':
        data_dict = {
            'designer_user': request.POST['designer_id'],
            'customer_user': request.user,
            'message': request.POST['message']
        }

        DesignerMessage.objects.create(**data_dict)
        messages.success(request, 'Messeage sent successfully')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def myMessageList(request):
    mymessages = DesignerMessage.objects.filter(designer_user=request.user.id)
    customerMessages = DesignerMessage.objects.filter(customer_user=request.user.id)
    users = User.objects.all()
    print(messages)
    diction = {
        'title': 'Messages',
        'mymessages': mymessages,
        'customerMessages': customerMessages,
        'users': users
    }
    return render(request, 'App_Dashboard/messages.html', context=diction)


def designerMessageReply(request, message_id):
    message = DesignerMessage.objects.get(pk=message_id)
    editReplyFrom = DesignerMessageFrom(instance=message)

    if request.method == 'POST':
        form = DesignerMessageFrom(request.POST, 'request.FILES', instance=message)
        if form.is_valid():
            form.save(commit=True)
            messages.info(request, 'Message replied Successfully')
            return HttpResponseRedirect(reverse('App_Dashboard:myMessageList'))
    diction = {
        'editReplyFrom': editReplyFrom
    }

    return render(request, 'App_Dashboard/reply_message.html', context=diction)

templates/App_Dashboard/designers_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}

{% block css_block %}
    .Designer {
        width: 550px;
        border: 1px solid #ccc;
        padding: 25px;
    }
{% endblock %}

{% block body_block %}
<center>
    <div class="Designer">
        <h3>Add Designer Info</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ designer_info_form|crispy }}
            <br>
            <input type="submit" value="Add" name="submit" class="btn btn-primary" style="width: 100%">
        </form>
    </div>
</center>
{% endblock %}

templates/App_Dashboard/edit_country.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}

{% block css_block %}
.country {
width: 550px;
border: 1px solid #ccc;
padding: 25px;
}
{% endblock %}

{% block body_block %}
<center>
    <div class="country">
        <h3>Edit Country</h3>
        <form method="post" class="form-control">
            {% csrf_token %}
            {{ edit_form|crispy }}
            <br>
            <input type="submit" value="Update" name="submit" class="btn btn-info " style="width: 100%">
        </form>
    </div>
</center>



{% endblock %}

templates/App_Dashboard/edit_designers.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{ title }} {% endblock %}

{% block css_block %}
    .country {
    width: 550px;
    border: 1px solid #ccc;
    padding: 25px;
    }
{% endblock %}

{% block body_block %}
<center>
    <div class="country">
        <h3>Edit Designer Info</h3>
        <form method="post" class="form-control">
            {% csrf_token %}
            {{ edit_form|crispy }}
            <br>
            <input type="submit" value="Update" name="submit" class="btn btn-info " style="width: 100%">
        </form>
    </div>
</center>
{% endblock %}

templates/App_Dashboard/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'gfonts.html' %}
    <link rel="stylesheet" href="/static/css/style.css" />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="/static/css/style3.css" />
    <link rel="stylesheet" href="/static/css/style5.css" />
    
    {% include 'footer_scripts.html' %}

    <title>Havenly</title>
  </head>
  <body>

    <style>
      .h-align{
        display: block !important;
        justify-content: center !important;
      }
    </style>
    <!-- NAV-BAR -->
    {% include 'navbar.html' %}
    <!-- END -->
    <div
      id="carouselExampleCaptions"
      class="carousel slide carousel-fade"
      data-ride="carousel"
    >
      <ol class="carousel-indicators">
        <li
          data-target="#carouselExampleCaptions"
          data-slide-to="0"
          class="active"
        ></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/media/images/img-3.jpg" class="d-block w-100" alt="..." />
          <div class="background-overlay"></div>
          <div class="carousel-caption">
            <h5 class="display-4 h4-md mb-4 font-weight-bold">
              Make room for better living
            </h5>
            <p class="h4 mb-5 pb-3 text-white-50">
              Stunning interior design services, now within reach.
            </p>
            <a
              href="{% url 'App_Dashboard:view_posts' %}"
              class="btn btn-lg btn-danger"
              >View More</a
            >
          </div>
        </div>
        <div class="carousel-item">
          <img src="/media/images/img-4.jpg" class="d-block w-100" alt="..." />
          <div class="background-overlay"></div>
          <div class="carousel-caption">
            <h5 class="display-4 mb-4 font-weight-bold">
              Make room for better living
            </h5>
            <p class="h4 mb-5 pb-3 text-white-50">
              Stunning interior design services, now within reach.
            </p>
            <a
              href="{% url 'App_Dashboard:view_posts' %}"
              class="btn btn-lg btn-danger"
              >View More</a
            >
          </div>
        </div>
        <div class="carousel-item">
          <img src="/media/images/img-2.jpg" class="d-block w-100" alt="..." />
          <div class="background-overlay"></div>
          <div class="carousel-caption">
            <h5 class="display-4 mb-4 font-weight-bold">
              Make room for better living
            </h5>
            <p class="h4 mb-5 pb-3 text-white-50">
              Stunning interior design services, now within reach.
            </p>
            <a
              href="{% url 'App_Dashboard:view_posts' %}"
              class="btn btn-lg btn-danger"
              >View More</a
            >
          </div>
        </div>
      </div>
      <a
        class="carousel-control-prev"
        href="#carouselExampleCaptions"
        role="button"
        data-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a
        class="carousel-control-next"
        href="#carouselExampleCaptions"
        role="button"
        data-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>

    {% comment %} Posts Start {% endcomment %}
    
      <!-- START BLOG -->
	<section id="blog" class="blog_section">
		<div class="container">
			<div class="row">
				<div class="col-md-12" data-aos="fade-up">
					<div class="section-title text-center wow zoomIn">
						<h2>Posts</h2>
						<span></span>
						<p>Posts by Our Designers</p>
					</div>
				</div><!-- END COL -->
			</div><!-- END ROW -->

			<div class="row">
        {% for post in posts %}
        {% if forloop.counter <= 3 %}
				<div class="col-lg-4 col-md-6" data-aos="fade-up">
					<div class="single_blog">
						<div class="blog_image">
							<img class="blog-photo" alt="Blog Photo" src="/media/{{ post.image }}"  width="600px" />
							<span class="post_date">{{ post.upload_date}}</span>
						</div>
						<div class="blog-text">
							<h4><a href="{% url 'App_Dashboard:view_post' post_id=post.id %}">
                {% if not designer.full_name %}
                {{ post.author.username }}
                {% else %}
                {{ post.full_name }}
                {% endif %}</a></h4>
							<p>{{ post.description|truncatewords:10 }}</p>
              <div class="row justify-content-center">
                <a
                href="{% url 'App_Dashboard:view_post' post_id=post.id %}"
                class="btn btn-lg btn-danger btn-center h-align col-3"
                >View</a>
              </div>
              {% comment %} <a href="{% url 'App_Dashboard:view_post' post_id=post.id %}" class="btn btn-default btn-home-bg">View</a> {% endcomment %}
						</div>
					</div>
				</div>
				<!--- END COL -->
        {% endif %}
        {% empty %}
        <div class="container"><h3 align="center">NO POST FOUND</h3></div>
        {% endfor %}
        
			</div>
      {% if posts is not None %}
      <div class="row justify-content-center">
        <a
        href="{% url 'App_Dashboard:view_posts' %}"
        class="btn btn-lg btn-danger btn-center h-align col-2"
        >See All Posts</a>
      </div>
      {% endif %}
      
			<!--- END ROW -->
		</div>
		<!--- END CONTAINER -->
	</section>
	<!-- END BLOG -->
    {% comment %} Testimony AND galary {% endcomment %}

      <section class="section-testimonials">
        <div class="testimonial-container">
          <span class="subheading">Testimonial</span>
          <h2 class="heading-secondary">Once you try it,you can't go back</h2>
          <div class="textimonials">
            <figure class="textimonial">
              <img
                class="testimonial-img"
                src="/media/img/customers/dave.jpg"
                alt="customer img"
              />
              <blockquote class="testimonial-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Tristique magna sit amet purus gravida quis blandit turpis
                cursus
              </blockquote>
              <p class="testimonial-name">&mdash; Dave Bryson</p>
            </figure>

            <figure class="textimonial">
              <img
                class="testimonial-img"
                src="/media/img/customers/ben.jpg"
                alt="customer img"
              />
              <blockquote class="testimonial-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Tristique magna sit amet purus gravida quis blandit turpis
                cursus
              </blockquote>
              <p class="testimonial-name">&mdash;Ben Hadley</p>
            </figure>

            <figure class="textimonial">
              <img
                class="testimonial-img"
                src="/media/img/customers/steve.jpg"
                alt="customer img"
              />
              <blockquote class="testimonial-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Tristique magna sit amet purus gravida quis blandit turpis
                cursus!
              </blockquote>
              <p class="testimonial-name">&mdash; Steve Miller</p>
            </figure>

            <figure class="textimonial">
              <img
                class="testimonial-img"
                src="/media/img/customers/hannah.jpg"
                alt="customer img"
              />
              <blockquote class="testimonial-text">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Tristique magna sit amet purus gravida quis blandit turpis
                cursus
              </blockquote>
              <p class="testimonial-name">&mdash; Hannah Smith</p>
            </figure>
          </div>
        </div>
        <div class="gallery">
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-1.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-2.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-3.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-4.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-5.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-6.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-7.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-8.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-9.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-10.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-11.jpg" alt="#" />
          </figure>
          <figure class="gallery-item">
            <img src="/media/img/gallery/gallery-12.jpg" alt="#" />
          </figure>
        </div>
      </section>
      {% comment %}
    </div>
    {% endcomment %} {% comment %} contact {% endcomment %}
    <div class="contact-container-body" id="contact-home">
      <div class="contact-container">
        <div class="left-col-contact">
          <!-- <img class="logo" src="gallery-2.jpg" /> -->
        </div>
        <div class="right-col-contact">
          <h1>Contact us</h1>
          <p>
            Feel Free to Contact Us. Leave Your Message Here. We Will Gwt Back
            to You As Soon As Possible.
          </p>

          <form
            id="contact-form"
            method="post"
            action="{% url 'App_Dashboard:contact_us' %}"
          >
            {% csrf_token %}
            <label for="name">Full name</label>
            <input
              type="text"
              id="name"
              name="name"
              placeholder="Your Full Name"
              required
            />
            <label for="email">Email Address</label>
            <input
              type="email"
              id="email"
              name="email"
              placeholder="Your Email Address"
              required
            />
            <label for="contact">Your Phone Number</label>
            <input
              type="Phone"
              id="email"
              name="contact"
              placeholder="Your Phone Number"
              required
            />
            <label for="message">Message</label>
            <textarea
              rows="6"
              placeholder="Your Message"
              id="message"
              name="message"
              required
            ></textarea>
            <button type="submit" id="submit" name="submit">Send</button
            ><!--</a>-->
          </form>
          <div id="error"></div>
          <div id="success-msg"></div>
        </div>
      </div>
    </div>

    <!-- tawk.to live chat -->
    <!--Start of Tawk.to Script-->

    <!--End of Tawk.to Script-->

    {% comment %} footer {% endcomment %} {% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    {% comment %} <script src="https://kit.fontawesome.com/abffacff72.js" crossorigin="anonymous"></script> {% endcomment %}
    <script src="/static/js/navbar.js"></script>
    <script src="/static/js/posts_scripts.js"></script>
  </body>
</html>