App_Dashboard/urls.py
from django.urls import path
from App_Dashboard import views

app_name = 'App_Dashboard'

urlpatterns = [
    path('', views.home, name="home"),

    path('designer_info/', views.designer_info, name='designer_info'),
    path('add_designer/', views.add_designer, name='add_designer'),
    path('view_designer/<int:designer_id>/', views.view_designer, name='view_designer'),
    path('edit_designer/<int:designer_id>/', views.edit_designer, name='edit_designer'),
    path('delete_designer/<int:designer_id>/', views.delete_designer, name='delete_designer'),

    path('post/', views.post, name='post'),
    path('view_posts/', views.view_posts, name='view_posts'),
    path('view_post/<int:post_id>/', views.view_post, name='view_post'),
    path('edit_post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),


    path('react_post/<int:post_id>/', views.react_post, name='react_post'),

    path('reply/', views.reply, name='reply'),
    path('desginerMessage/', views.desginerMessage, name='desginerMessage'),
    path('messageReply/<int:message_id>', views.designerMessageReply, name='messageReply'),
    path('myMessageList/', views.myMessageList, name='myMessageList'),

    path('contact_us/', views.contactUs, name='contact_us'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = "App_Login"

urlpatterns = [
    path('edit/', views.edit_profile, name='edit'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('users/', views.users, name='users'),
    path('log-sign/', views.log_sign, name='log-sign'),
    path('login/', views.login, name='login'),
]

my_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from App_Dashboard import views

admin.site.site_header = 'Havenly'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('App_Login.urls')),
    path('dashboard/', include('App_Dashboard.urls')),
    path('', views.home, name="home")
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>{% block title_block %} {% endblock %} / My Project</title>
      <style>
          {% block css_block %}

          {% endblock %}
      </style>

<!--    </style>-->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
  <body>
    {% include 'navbar.html' %}
    <div class="" style="padding-top: 30px;">
      {% block body_block %}

      {% endblock %}
    </div>
    {% include 'footer.html' %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/footer.html
<!-- Site footer -->
<footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-6">
          <h6>Happiness Guarantee</h6>
          <p class="text-justify">
            If you're not happy with our design, we're not happy. We work
            tirelessly to make sure your Havenly design experience is
            delightful. That's why we offer the Havenly Happiness Guarantee.
          </p>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>Categories</h6>
          <ul class="footer-links">
            <li>
              <a href="#">Careers</a>
            </li>
            <li>
              <a href="#">Design Careers</a>
            </li>
            <li>
              <a href="#">Reviews</a>
            </li>
            <li>
              <a href="#">Pricing</a>
            </li>
            <li>
              <a href="#">Stories</a>
            </li>
            <li>
              <a href="#">Press Inquiries</a>
            </li>
          </ul>
        </div>

        <div class="col-xs-6 col-md-3">
          <h6>Quick Links</h6>
          <ul class="footer-links">
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact Us</a></li>
            <li>
              <a href="#">Contribute</a>
            </li>
            <li>
              <a href="#">Privacy Policy</a>
            </li>
            <li><a href="#">Follow @thehavenly</a></li>
          </ul>
        </div>
      </div>
      <hr />
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-6 col-xs-12">
          <p class="copyright-text">
            2022 <a href="#">Havenly</a>. Inc., All Rights Reserved.
          </p>
        </div>

        <div class="col-md-4 col-sm-6 col-xs-12">
          <ul class="social-icons">
            <li>
              <a class="facebook" href="#"
                ><ion-icon name="logo-facebook"></ion-icon
              ></a>
            </li>
            <li>
              <a class="twitter" href="#"
                ><ion-icon name="logo-twitter"></ion-icon
              ></a>
            </li>
            <li>
              <a class="dribbble" href="#"
                ><ion-icon name="logo-dribbble"></ion-icon
              ></a>
            </li>
            <li>
              <a class="linkedin" href="#"
                ><ion-icon name="logo-linkedin"></ion-icon
              ></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>

templates/footer_scripts.html
<!-- Icon  -->
<script src="https://unpkg.com/ionicons@latest/dist/ionicons.js"></script>

<!-- Bootstrap CSS -->
<link
  rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
  crossorigin="anonymous"
/>
<link rel="stylesheet" href="/static/css/style4.css" />

templates/gfonts.html
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="stylesheet" href="/static/css/posts.css" />
    <link
      href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,600,700"
      rel="stylesheet"
    />
    <link
      href="http://fonts.googleapis.com/css?family=Montserrat:300,400,700"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300i,400,400i,600,600i,700,700i"
      rel="stylesheet"
    />

templates/messages.html
{% if messages %}
{% for message in messages %}
<div class="container-fluid p-0">
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" >
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
</div>
{% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg fixed-top navbar-dark py-3 bg-scollme">
    <div class="container">
      <a
        class="navbar-brand font-weight-bold text-uppercase"
        href="http://127.0.0.1:8000/"
        >Havenly</a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto font-weight-bold">
          <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/"
              >Home</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Dashboard:view_posts' %}">Blog Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:users' %}">Designer List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/#contact-home">Contact</a>
          </li>
          {% if user.is_authenticated  %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Dashboard:myMessageList' %}">My Messages</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:profile' %}">Hi, <b>{{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'App_Login:log-sign' %}">Sign In/Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>